# fly.toml app configuration file generated for collectibles on 2024-06-30T10:15:01+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'collectibles'
primary_region = 'sin'

[build]
  [build.args]
    GO_VERSION = '1.22.3'

[env]
  COLLECTIBLES_PORT = '8080'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2

[mounts]
  source = "collectibles_data"
  destination = "/data"
  auto_extend_size_increment = "5GB"
  auto_extend_size_limit = "500GB"
  auto_extend_size_threshold = 80
